#+DATE: [2020-01-07 Tue] 
#+TITLE: CHE 573 University of Alberta: DIGITAL SIGNAL PROCESSING FOR CHEMICAL ENGINEERS
#+OX-IPYNB-KEYWORD-METADATA: keywords
#+KEYWORDS: System, Discretization, z-transform

# You need this to be first so it exports correctly
#+BEGIN_SRC ipython

#+END_SRC

#+RESULTS:
: # Out[1]:

* Impulse Response Representation of DT Systems

  In previous section, we introduced that a DT system can be represented by its inputs and outputs. In the input-output representation, we know that the output of a system can be determined by its previous outputs and inputs. In that representation, we need to know all the inputs and all the previous outputs. Sometimes, this is not convenient. In this section, we introduce another important DT system representation: impulse response representation. Using this representation, we can determine the output of a system directly (without evaluating the previous outputs) for any given input sequence.

** Impulse response
   First, we need to introduce impulse response. The impulse response $h(n)$ of an linear time-invariant (LTI) system \(T\) is defined as the response of the system to the unit impulse (or sample) signal $\delta(n)$:

   \[h(n) = T\{\delta(n)\} \]
   
** Response of LTI DT systems

   Note that in this section, we again assume the system has zero initial condition (i.e., \(y(n)=0\) for \(n < 0\) ). Recall that the sequence of any arbitrary signal can be represented as:

   \[x(n) = \sum_{k=-\infty}^{\infty}x(k)\delta(n-k)\]

   Since the system we consider is time-invariant, if

   \[h(n)=T\{\delta(n)\}\]
   
   Then,

   \[T\{\delta(n-k)\}=h(n-k)\]
   
   for any \(k\). Furthermore, the system is linear,

   \[\begin{array}{ccc} y(n) & = & T \{x(n)\} = T\{\sum_{k=-\infty}^{\infty}x(k)\delta(n-k)\}\\ &=& \sum_{k=-\infty}^{\infty}T\{x(k)\delta(n-k)\}\\ &=&\sum_{k=-\infty}^{\infty}x(k)T\{\delta(n-k)\}  \end{array} \]

   From the above equations, we can obtain that the response of the system to the input sequence $x$ is:

   \[y(n) = \sum_{k=-\infty}^{\infty}x(k)h(n-k)\tag{0}\label{eqn:ch2:convolution}\]
   
   For causal systems, the above equation can be simplified:

   \[y(n) = \sum_{k=-\infty}^{n}x(k)h(n-k)\tag{1}\label{eqn:ch2:convolution1}\]
   
   This implies that the response of an LTI system to an arbitrary input sequence can be calculated using the system's impulse response. Equation~(\ref{eqn:ch2:convolution}) is also called the /convolution sum/ of the \(x\) and \(h\). This operation is denoted by \(*\). That is,

   \[y(n) = \sum_{k=-\infty}^{n}x(k)h(n-k) = x(n)*h(n)\tag{2}\label{eqn:ch2:convolution2}\]
   
   The operation of convolution is {\em commutable} which means:

   \[y(n)=x(n)*h(n) = h(n)*x(n) =\displaystyle\sum_{k=0}^{\infty}h(k)x(n-k)\tag{3}\label{eqn:ch2:convolution3}\]
   
   To summarize, the response of an LTI system to an arbitrary input sequence can be calculated using the convolution sum of the input sequence and the system's impulse response.

** Example
   Suppose that the impulse response of a causal LTI system is:

   \[\begin{array}{rcl}h(n)=\{\hspace{-3mm}&1&\hspace{-3mm},2,1,-1\}\\&\uparrow&\end{array}\]
   Determine its response to:

   \[\begin{array}{rcl}x(n)=\{\hspace{-3mm}&1&\hspace{-3mm},2,3,1\}\\&\uparrow&\end{array}\]
   
   Note that these are sequences of values starting from $n=0$ and the arrow indicates the time instant $n=0$. If no arrow is used, it means the first value corresponds to $n=0$.

   Using convolution sum, we can write that:

   \[y(n) = x(n)*h(n) = \sum_{k=-\infty}^{n}x(k)h(n-k)\]
   
   From the definitions of $h$ and \(x\), it can be seen that for \( n<0\) and \(n\geq 4\), the signals are not defined. In this course, we will treat these undefined values as zero. Strictly speaking, `undefined' and `zero' are two different things. However, treating `undefined' as zero, greatly simplifies the calculation of convolution sum and all the other calculations in this course. Let us use the index of \(x\) as a reference to determine the range of \(k\) that should be considered. From the definition of \(x\), we can find that we only have to consider \(0\leq k\leq 3\). For all the other \(k\), \(x(k)\) will have a zero value. Therefore, the above equation can be simplified to the following:

   \[ y(n) = x(n)*h(n) = \sum_{k=0}^{n}x(k)h(n-k)\]
   If \(n=0\), we have

   \[\begin{array}{rcl}y(0) & = & \sum_{k=0}^{0}x(k)h(-k)\\& = & x(0)h(0)\\& = & 1\cdot 1\\& = & 1\end{array}\]
   
   Similarly, we can evaluate \(y(1)\), \(y(2)\), \(\cdots\)
   
   \[\begin{array}{rcl}y(1) & = & \sum_{k=0}^{1}x(k)h(1-k)\\& = & x(0)h(1) + x(1)h(0)\\& = & 1\cdot 2 + 2\cdot 1\\& = & 4\end{array}\]

   \[\begin{array}{rcl}y(2) & = &\sum_{k=0}^{2}x(k)h(2-k)\\& = & x(0)h(2) + x(1)h(1) + x(2)h(0)\\& = & 1\cdot 1 + 2\cdot 2 + 3\cdot 1\\& = & 8\end{array}\]

   \[\begin{array}{rcl}y(3) & = &\sum_{k=0}^{3}x(k)h(3-k)\\& = & x(0)h(3) + x(1)h(2) + x(2)h(1) + x(3)h(0)\\& = & 1\cdot (-1) + 2\cdot 1 + 3\cdot 2 + 1\cdot 1\\& = & 8\end{array}\]
   
   The output sequence is:

   \[y(n)=\left\{1,4,8,8,3,-2,-1\right\}\]
   
   Remark: Note that the convolution sum is based on zero initial condition of the system (i.e., \(y(n)=0\) for \(n<0\)). When the initial condition is not zero, we need to consider the effects of the initial condition as well.

   

** Causality condition
   In the previous section, from eqn:ch2:convolution to eqn:ch2:convolution1, we simply used the fact that there should be no future inputs in the output of a causal system. If we look into eqn:ch2:convolution, we can find a condition for the causality of LTI systems. Let us write eqn:ch2:convolution into two parts as follows:

   \[y(n) =  \sum_{k=-\infty}^{\infty}x(k)h(n-k) = \displaystyle\sum_{k=-\infty}^{n}x(k)h(n-k)+\displaystyle\sum_{k=n+1}^{\infty}x(k)h(n-k)\tag{3}\label{eqn:ch2:causality}\]
   
   For a causal system, we know that the second term on the right should not appear since it involves all the future inputs. If we look at the corresponding $h$ values, we can find the second term including the following elements of \(h\):

   \[h(-1),\;h(-2),\;h(-3),\;\ldots\]
   
   Since \(x(k)\) for \(k\geq n\) could be arbitrary values, the condition that ensures causality of the system is:

   \[h(-1) = 0,\;h(-2)=0,\;h(-3)=0,\ldots\]
   
   That is:

   \[h(n)=0,\;for\; all\;\; n<0\]
   
   This condition is actually a necessary and sufficient condition. To summarize the above result, an LTI system is causal if and only if its impulse response must be zero for \(n<0\).



* Summary

 - We introduce impulse response

 - We calculate impulse response by convolution


